WIP: Group 7 python extractors
NYCPlanning/db-facilities pull request #363
Opened 2021-04-12 18:21 UTC by mgraber

2021-04-12 22:05 UTC, AmandaDoyle commented on facdb/pipelines.py
> +        df.county_description.isin(["NEW YORK", "KINGS", "BRONX", "QUEENS", "RICHMOND"])
Should we always case county as proper case or upper case so capitalization doesn't become an issue?

2021-04-12 22:05 UTC, AmandaDoyle approved these changes

2021-04-14 14:09 UTC, SPTKL commented on facdb/pipelines.py
> +    df = df[df.county.isin(["New York", "Kings", "Bronx", "Queens", "Richmond"])]
We should also pass in a borough field based on county into function 1B to retain maximal info

2021-04-15 19:29 UTC, SPTKL requested changes
transform county -> borough and pass into Function1B

2021-04-16 14:05 UTC, SPTKL approved these changes

2021-04-16 14:06 UTC, merged