updating format for values
NYCPlanning/db-facilities pull request #493
Opened 2021-06-17 00:00 UTC by AmandaDoyle

2021-06-17 13:57 UTC, SPTKL commented on facdb/sql/_create_facdb.sql
> +    TRIM(regexp_replace(facdb_address.streetname, '\s+', ' ', 'g')) as streetname,
this should be done within the facdb_address table 
https://github.com/NYCPlanning/db-facilities/blob/develop/facdb/sql/_create_facdb_address.sql
we want to make sure all the logic/cleaning happens in the same place

2021-06-17 13:58 UTC, SPTKL commented on facdb/sql/_create_facdb.sql
> +    LPAD(facdb_spatial.council,2,'0') as council,
this should happen in 
https://github.com/NYCPlanning/db-facilities/blob/5f88854eed5dbc2bea2ec47b277f804825eef6c8/facdb/sql/_create_facdb_spatial.sql#L41-L59
similar to bin formatting, all other districts formating should be done here ^

2021-06-17 14:00 UTC, SPTKL requested changes
move logic to their corresponding sql files, so that we can address issues more upstream

2021-06-21 15:44 UTC, mgraber commented
> move logic to their corresponding sql files, so that we can address issues more upstream

The field `schooldist` has values with length less than 2 digits in 31 data sources:

- dca_operatingbusinesses
- dcla_culturalinstitutions
- dcp_colp
- dcp_pops
- dcp_sfpsd
- doe_lcgms
- dohmh_daycare
- dot_bridgehouses
- dot_mannedfacilities
- dot_pedplazas
- dot_publicparking
- dpr_parksproperties
- dsny_fooddrop
- dsny_garages
- dsny_leafdrop
- dsny_specialwastedrop
- dsny_textiledrop
- dycd_afterschoolprograms
- fdny_firehouses
- hhc_hospitals
- nycha_communitycenters
- nypl_libraries
- nysdec_lands
- nysdoh_healthfacilities
- nysed_activeinstitutions
- nysomh_mentalhealth
- nysparks_historicplaces
- sbs_workforce1
- usdot_airports
- usdot_ports
- usnps_parks

The field `council` has values with length less than 2 digits in 29 data sources:

- dca_operatingbusinesses
- dcla_culturalinstitutions
- dcp_colp
- dcp_pops
- dcp_sfpsd
- dohmh_daycare
- dot_bridgehouses
- dot_mannedfacilities
- dot_pedplazas
- dot_publicparking
- dpr_parksproperties
- dsny_fooddrop
- dsny_garages
- dsny_leafdrop
- dsny_specialwastedrop
- dsny_textiledrop
- dycd_afterschoolprograms
- fdny_firehouses
- hhc_hospitals
- nycha_communitycenters
- nypl_libraries
- nysdoh_healthfacilities
- nysed_activeinstitutions
- nysomh_mentalhealth
- nysparks_historicplaces
- sbs_workforce1
- usdot_airports
- usdot_ports
- usnps_parks

The field `policeprct` has values with length less than 3 digits in 37 data sources:

- bpl_libraries
- dca_operatingbusinesses
- dcla_culturalinstitutions
- dcp_colp
- dcp_pops
- dcp_sfpsd
- doe_busroutesgarages
- doe_lcgms
- dohmh_daycare
- dot_bridgehouses
- dot_mannedfacilities
- dot_pedplazas
- dot_publicparking
- dpr_parksproperties
- dsny_electronicsdrop
- dsny_fooddrop
- dsny_garages
- dsny_leafdrop
- dsny_specialwastedrop
- dsny_textiledrop
- dycd_afterschoolprograms
- fdny_firehouses
- hhc_hospitals
- nycha_communitycenters
- nycha_policeservice
- nypl_libraries
- nysdec_lands
- nysdoh_healthfacilities
- nysdoh_nursinghomes
- nysed_activeinstitutions
- nysomh_mentalhealth
- nysparks_historicplaces
- nysparks_parks
- sbs_workforce1
- usdot_airports
- usdot_ports
- usnps_parks

Is it worth padding in each of these individual sql files?

2021-06-22 18:28 UTC, merged