Default latest
NYCPlanning/db-facilities pull request #539
Opened 2022-04-22 14:57 UTC by SashaWeinstein

# Pull latest version from data library
This is most substantial change we've made for this build as it effects all datasets. 
This change was prompted as I forgot to change the dataset version in datasets.yml during the dataloading step. Our other data products default to take the latest version of data from data library and can be adapted to take a particular version if need be. This seems to be a better approach so facdb was changed to default to latest version if no version is specified in datasets.yml

A change to a .sql file that should only be merged via another PR snuck in here, shouldn't mess anything up

2022-04-22 15:11 UTC, mbh329 commented on facdb/datasets.yml
> -    version: 20210402
This won't work, it needs to be pointed to the older version

2022-04-22 15:12 UTC, mbh329 requested changes
Only thing is to change the dsny_leafdrop to point to the old version as I haven't fixed it yet

2022-04-22 15:24 UTC, td928 commented
after Max's comment about leafdrop is addressed should be good to go?

2022-04-22 15:38 UTC, td928 approved these changes

2022-04-22 15:40 UTC, td928 commented
After approval realize there is merge conflicts for some empty lines in .devcontainer/docker-compose.yml

2022-04-22 15:42 UTC, SashaWeinstein commented
addressing merge conflicts now. removed 11 from postgres client in dockerfile, dealing with some changes to poetry lock. seeing if everything works now

2022-04-22 16:00 UTC, mbh329 approved these changes

2022-04-22 16:25 UTC, merged

2022-05-02 21:35 UTC, AmandaDoyle commented
I apologize for not weighing in on this sooner.  Let's see how this works out.  The reason why a specific version was set for each dataset was because of the lengthy QA and iteration process, so if a dataset was updated during a review process it could cause us to have to update the ingestion process and/or introduce new anomalies in a QAQC report, further slowing the review process.